# Generated by Django 4.2 on 2024-06-06 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boxitem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=50)),
                ('item_amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Boxtyp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typ_name', models.CharField(max_length=50)),
                ('typ_description', models.CharField(max_length=200)),
                ('boxitems', models.ManyToManyField(blank=True, related_name='boxtyp_item', to='inventur.boxitem')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loc_name', models.CharField(max_length=50)),
                ('loc_description', models.CharField(max_length=200)),
                ('boxtyp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventur.boxtyp')),
            ],
        ),
    ]
