# Generated by Django 4.2 on 2024-06-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventur', '0004_inventur_inv_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventur',
            name='created_by',
            field=models.CharField(default='Sunrise Roboter', max_length=50),
        ),
    ]
